name: 'swishsalon '
favicon: null
layout_spectrum: 0.1983865941874683
typography_spectrum: 0.9500133970286697
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.774664121447131
  lightness: 0.34876948734745383
  saturation: 0.2636580150574446
  rhythmicContrast: 0.8247477076947689
purpose: []
